name: Build and push docker image
on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: jani888/gitea-runner:latest
    steps:
      - run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login gitea.sudsy.com -u ${{secrets.REGISTRY_USER}} --password-stdin
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: docker build . -t gitea.sudsy.com/competitors/${{gitea.event.repository.name}}:latest
      - run: docker push gitea.sudsy.com/competitors/${{gitea.event.repository.name}}:latest
